- name: Stop Gitlab using Docker Compose
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop Gitlab Compose stack
      community.docker.docker_compose:
        project_src: ~/workspace/gitlab
        state: absent
        files:
          - docker-compose.yml


