- name: Install Docker and Docker Desktop
  hosts: localhost
  vars:
    docker_packages:
      debian: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
      centos: [yum-utils, device-mapper-persistent-data, lvm2]
      ubuntu: [apt-transport-https, ca-certificates, curl, gnupg, lsb-release]
      darwin: [brew]
      redhat: [yum-utils, device-mapper-persistent-data, lvm2]
      windows: []
    #docker_desktop_url: "https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe"
  tasks:
    - name: Install Docker Desktop
      win_chocolatey:
        name: docker-desktop
        state: present
      when: ansible_distribution == 'Windows' or ansible_distribution is search('CYGWIN', ansible_distribution) | bool
      
    - name: Install Docker and Docker Compose on Linux and macOS
      block:
        - name: Install Docker dependencies
          package:
            name: "{{ docker_packages[ansible_distribution] }}"
            state: present
          when: ansible_distribution in docker_packages.keys()

        - name: Add Docker GPG key
          apt_key:
            url: https://download.docker.com/linux/{{ ansible_distribution }}/gpg
            state: present
          when: ansible_distribution in ['debian', 'ubuntu']

        - name: Add Docker repository
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution }} {{ ansible_distribution_release }} stable
            state: present
          when: ansible_distribution in ['debian', 'ubuntu']

        - name: Install Docker on CentOS and Red Hat
          yum:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
          when: ansible_distribution in ['centos', 'redhat']

        - name: Install Docker on macOS
          homebrew:
            name: docker
            state: present
          when: ansible_distribution == 'darwin'

        - name: Install Docker Compose
          pip:
            name: docker-compose
            state: present
          when: ansible_distribution in ['debian', 'ubuntu', 'centos', 'redhat', 'darwin']

      when: ansible_distribution != 'Windows'
